//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sandbox.bca.co.id.
        /// </summary>
        internal static string base_url_bca {
            get {
                return ResourceManager.GetString("base_url_bca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string limit_data_count {
            get {
                return ResourceManager.GetString("limit_data_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U2FsdGVkX196KB2Tl4gxHCEkqpTvbhm7763k5txzGPmZkYdN1ruB47MFplVTSvtr.
        /// </summary>
        internal static string sec_key_http {
            get {
                return ResourceManager.GetString("sec_key_http", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat_notransaksi.
        /// </summary>
        internal static string sec_key_notransaksi {
            get {
                return ResourceManager.GetString("sec_key_notransaksi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat_session.
        /// </summary>
        internal static string sec_key_session {
            get {
                return ResourceManager.GetString("sec_key_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat_orderin_user.
        /// </summary>
        internal static string sec_key_userlogin {
            get {
                return ResourceManager.GetString("sec_key_userlogin", resourceCulture);
            }
        }
    }
}
